/- LocalClosure2.lean — core Lean only (kernel `decide` on Nat).

   Further instances of the coincidence-counting local law
   (paper §5, local closure): b = 4 at p = 7 (343 lock cubes)
   and b = 5 at p = 5 (625 lock cubes), same definitions as
   LocalClosure.lean.  Namespaced LC2 to avoid clashing with
   LocalClosure.lean's root-level definitions when both are
   library roots.

   重合计数局部律的进一步实例 (论文 §5): b=4, p=7 (343 锁类) 与
   b=5, p=5 (625 锁类); 定义与 LocalClosure.lean 相同, 置于 LC2
   命名空间以避免根级重名.                                        -/

namespace LC2

def powMod (x n p : Nat) : Nat :=
  match n with
  | 0 => 1 % p
  | Nat.succ m => (x * powMod x m p) % p

def invMod (x p : Nat) : Nat := powMod x (p - 2) p

/-- The chain points n_1, n_2, ..., n_b (mod p) generated by the
    lattice slopes `a` and lock vector `j`. -/
def chainPts (p n1 : Nat) (a j : List Nat) : List Nat :=
  let step := fun (st : Nat × List Nat) (aj : Nat × Nat) =>
    let nxt := (aj.1 * st.1 + aj.2) % p
    (nxt, st.2 ++ [nxt])
  ((a.zip j).foldl step (n1, [n1])).2

/-- Number of admissible chains: those with no point ≡ 0 (mod p). -/
def chainCount (p : Nat) (a j : List Nat) : Nat :=
  (List.range p).foldl (fun acc n1 =>
    if (chainPts p n1 a j).all (fun x => x % p ≠ 0)
    then acc + 1 else acc) 0

/-- Number of distinct forbidden offsets D(j) of the lock vector. -/
def distinctOffsets (p : Nat) (a j : List Nat) : Nat :=
  let Bs := chainPts p 0 a j
  let As := a.foldl (fun (l : List Nat) ai =>
    l ++ [(l.getLast! * ai) % p]) [1]
  let ds := (Bs.zip As).map
    (fun BA => (BA.1 * invMod BA.2 p) % p)
  ds.eraseDups.length

/-- b = 4, p = 7: N(j) = p − D(j) over the full 7³ lock cube. -/
def identity_b4_p7 : Bool :=
  (List.range 7).all (fun j1 =>
    (List.range 7).all (fun j2 =>
      (List.range 7).all (fun j3 =>
        chainCount 7 [2,3,4] [j1,j2,j3]
          = 7 - distinctOffsets 7 [2,3,4] [j1,j2,j3])))

/-- b = 5, p = 5: N(j) = p − D(j) over the full 5⁴ lock cube. -/
def identity_b5_p5 : Bool :=
  (List.range 5).all (fun j1 =>
    (List.range 5).all (fun j2 =>
      (List.range 5).all (fun j3 =>
        (List.range 5).all (fun j4 =>
          chainCount 5 [2,3,4,6] [j1,j2,j3,j4]
            = 5 - distinctOffsets 5 [2,3,4,6] [j1,j2,j3,j4]))))

theorem local_closure_b4_p7 : identity_b4_p7 = true := by decide
theorem local_closure_b5_p5 : identity_b5_p5 = true := by decide

end LC2
